# IMPORTS
from fontTools.ttLib import TTFont
from fontTools.pens.recordingPen import RecordingPen
from fontTools.ttLib.removeOverlaps import removeOverlaps
from fontPens.flattenPen import FlattenPen
import matplotlib.pyplot as plt
import os


class Character(object):
    def __init__(self, character, font_name):
        self.contours = [] # a list of contours in the form [[(x1, y1), (x2, y2)], ...]
        self.character = character
        self.font_name = font_name
        self.width = 0 #overridden with the width of the character

    def add_contour(self, contour):
        self.contours += [list(contour)] # gets a copy of the input contour

    def set_width(self, width_em):
        self.width = width_em

    def __repr__(self):
        output_str = self.font_name + ":" + self.character + "\n"
        num_contours = len(self.contours)
        num_points = 0
        for contour in self.contours:
            num_points += len(contour)
        output_str += "  " + str(num_contours) + " CONTOURS" + "\n"
        output_str += "  " + str(num_points) + " POINTS"
        return str(output_str)

    def plot(self):
        fig, axes = plt.subplots()
        for contour in self.contours:
            x, y = zip(*contour)
            axes.plot(x, y)
        axes.set_aspect('equal')
        plt.show()

    def write(self, precision = 5):
        '''Writes a character to a file.
        
        precision -- the number of digits past the decimal to round.
        '''

        # build font directory if doesn't already exist
        os.makedirs(self.font_name, exist_ok=True)
        filename = self.font_name + "/" + str(ord(self.character)) + ".txt"
        output_file = open(filename, "w")

        for contour in self.contours:
            for index, (x, y) in enumerate(contour):
                if(index == 0): output_string = "start "
                elif(index == (len(contour) - 1)): output_string = "stop "
                else: output_string = "point "
                output_string += (str(round(x, precision)) + " " + str(round(y, precision)) + "\n")
                output_file.write(output_string)
        output_file.close()
                
class Font(object):
    def __init__(self, font_file):
        self.thisFont = TTFont(font_file)
        removeOverlaps(self.thisFont)
        self.font_name_raw = font_file
        self.font_name, ext = os.path.splitext(font_file)
        self.glyphSet = self.thisFont.getGlyphSet()


        # extract font size information
        # an em is the abstract square in which a font character is drawn
        # we'll leave things in units of em for now, and then can simply multiply by mm to put into mm.

        self.units_per_em = self.thisFont["head"].unitsPerEm

    def convert_to_em(self, value_in_font_units):
        return value_in_font_units / self.units_per_em

    def get_character(self, character, segmentLength = 20):
        ''' Returns a Character object generated by the font.'''
        #get character name
        cmap = self.thisFont.getBestCmap()
        char_name = cmap[ord(character)]
        #get curves on the glyph
        recording = RecordingPen()
        flatten = FlattenPen(recording, approximateSegmentLength=segmentLength, segmentLines=True)
        self.glyphSet[char_name].draw(flatten)

        #load into a character
        this_character = Character(character, self.font_name)

        contour = []
        for op, args in recording.value:
            if op == "moveTo" or op == "lineTo": contour += [tuple([self.convert_to_em(coord) for coord in args[0]])]
            if op == "closePath":
                this_character.add_contour(contour)
                contour.clear()

        this_character.set_width(self.convert_to_em(self.glyphSet[char_name].width))
        return this_character

    def write(self, ascii_start = 32, ascii_end = 126, precision = 5):
        '''Writes the entire font to a new folder.'''

        print("GENERATING FONT " + self.font_name_raw)
        advance_string = ""
        for ascii_code in range(ascii_start, ascii_end+1):
            character = self.get_character(chr(ascii_code))
            character.write(precision)
            print(' WROTE CHARACTER "' + character.character + '"')
            advance_string += (str(ascii_code) + " " + str(round(character.width, precision)) + "\n")

        # write advance file to store character advance values
        os.makedirs(self.font_name, exist_ok=True)
        filename = self.font_name + "/" + "advance.txt"
        advance_file = open(filename, "w") 
        advance_file.write(advance_string)
        advance_file.close()
        print(' WROTE ADVANCE FILE')       


if __name__ == "__main__":
    testfont = Font("roboto.ttf")
    testfont.write()
    # char = testfont.get_character("a")
    # char.plot()
    



